run:
  timeout: 5m
  tests: true
  skip-dirs-use-default: false
  allow-parallel-runners: true
  go: '1.25.7'

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - ineffassign
    - misspell
    - errcheck
    - gosimple
    - unused
    - typecheck

linters-settings:
  govet:
    enable-all: true

  staticcheck:
    checks: ["all"]

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
